### PR TITLE
Added minimize to tray

### PR DESCRIPTION
**Pull request by elliot-forty-two**

### CODE REVIEW

**Comment by elliot-forty-two** [comment]
Let me try that again, only meant to include one of those commits

**Comment by akej74** [comment]
Thanks for your support, looking forward to add this when you are ready.

**Comment by elliot-forty-two** [comment]
Well the commits are ready but I havent used git in a while and have forgotten how branches and pull requests work. You can take the lot if you think they're OK and consistent with your plans for the app, or I can try and re-do the commits if you'd prefer.

**Comment by akej74** [comment]
OK, it looks great, please let me test it out and then I will make a new release!

**Pull request closed without merging**
